#!/usr/bin/env sh

out='packaged.zip'

rm -f "${out}"

zip --exclude \
  '*.min.*' \
  '*.xcf' \
  '*.zip' \
  '*LICENSE*' \
  '*README*' \
  '.git*' \
  '*bower.json' \
  'demo-resources/*' \
  'license' \
  'package' \
  'test*' \
  'tests*' \
  'screenshots*' \
  -r9 "${out}" .
