#!/usr/bin/env bash

outdir="./build"

# Use the values specified in `manifest.json` so we can specify them in one
# place: there!
main_js="$(jq --raw-output '.content_scripts[0].js[0]' manifest.json)"
main_css="$(jq --raw-output '.content_scripts[0].css[0]' manifest.json)"

# Ensure our output directory exists.
mkdir -p "${outdir}"

# Grab the current version and use it in the packaged file name.
version="$(jq --raw-output '.version' manifest.json)"
out="${outdir}/amazon-wish-list-total-${version}.zip"

# Build/copy the files we'll need to our build directory.
cp 'src/css/main.css' "${main_css}"
elm make 'src/elm/Main.elm' --output="${outdir}/main.js"

# Concatenate the shim file onto our build main file to create the `main.js`
# file we include in `manifest.json`. The shim boots the app, the rest is Elm
# and our code.
cat "src/js/shim.js" >> "${main_js}"

# Grab all the files we'll need from the manifest.
files="manifest.json $(jq '.content_scripts[0].js[],
                           .content_scripts[0].css[],
                           .icons[]' manifest.json | xargs)"

# Package up all the files together into a single archive.
zip --include ${files} -r -9 "${out}" .
